version: '2'
services:
    poc-app:
        image: poc
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://poc-postgresql:5432/poc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    poc-postgresql:
        extends:
            file: postgresql.yml
            service: poc-postgresql
