version: '2'
services:
    poc-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/poc/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=poc
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
