name: OPT START
on: [push, pull_request]
jobs:
    pipeline:
        name: optstart pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
        timeout-minutes: 40
        env:
            NODE_VERSION: 8.17.0
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 8.17.0
            - uses: actions/setup-java@v1
              with:
                  java-version: 1.8
            - name: Install node.js packages
              run: yarn install
            - name: Run backend test
              run: |
                  chmod +x gradlew
                  ./gradlew clean test -x webpack
            - name: Run frontend test
              run: yarn run test
            - name: Analyze code with SonarQube
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: |
                  if [ -n $SONAR_TOKEN ]; then
                      ./gradlew sonarqube --no-daemon -Dsonar.host.url=https://sonarcloud.io
                  else
                      echo No SONAR_TOKEN, skipping...
                  fi
            - name: Package application
              run: ./gradlew bootRepackage -Pprod -x test
            - name: Publish to GitHub Packages
              run: gradle publish --stacktrace --debug
              env:
                  USERNAME: ${{ github.actor }}
                  PASSWORD: ${{ secrets.GITHUB_TOKEN }}
